const promiseRetry = require('promise-retry');
const logger = require('./get-logger');

function retryFunction(func, args, options = { retries: process.env.NUM_RETRIES || 20 }) {
  logger.debug(`attempting to call function ${func.name}` + ((args) ? `with arguments ${args}` : ''));

  return promiseRetry(options, function (retry, number) {
    logger.debug(`attempt to call ${func.name} number ${number} of ${options.retries}`);
    return func(args)
      .catch(err => {
        logger.debug(`failed attempt to call ${func.name}` + (args ? ` with arguments ${JSON.stringify(args, undefined, 2)}` : '') + `, error: ${err}`);
        retry(err);
      });
  })
    .catch(err => {
      logger.error(`failed all attempts to call ${func.name}` + (args ? ` with arguments ${JSON.stringify(args, undefined, 2)}` : '') + `, error: ${err}`);
      throw err;
    });
}

module.exports = retryFunction;
